<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="/static/css/head.css">
</head>
<body>
<div class="navbar">
    <img src="/static/images/logo.png" class="logo-icon">
    <div class="brand">Электронный журнал ожидания</div>
    <nav>
        <ul>
            <li><a href="/profile">Личный кабинет</a></li>
<#--            <li><a href="/signIn">Вход</a></li>-->
<#--            <li><a href="/signUp">Регистрация</a></li>-->
        </ul>
    </nav>
</div>
</body>
</html>
