<html>
<meta charset="UTF-8">
<head>
    <title>Добро пожаловать!</title>
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
<div class="main">
    <div class="container">
        <div class="content">
            <h2>Для продолжения работы необходимо авторизоваться.</h2>
            <a href="/signIn" class="loginButton">Вход</a>
            <p>Если у вас нет аккаунта, то <a href="/signUp">зарегистрируйтесь</a>.</p>
        </div>
    </div>
</div>

</body>
</html>